-- Generated by Oracle SQL Developer Data Modeler 19.4.0.350.1424
--   at:        2020-05-19 03:45:38 EEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g

CREATE TABLE token (
    token_id    NUMBER(9) NOT NULL,
    user_token  VARCHAR2(253 BYTE) NOT NULL
);

ALTER TABLE token ADD CONSTRAINT token_pk PRIMARY KEY ( token_id );

CREATE TABLE user_table (
    user_id        NUMBER(9) NOT NULL,
    user_name      NVARCHAR2(15) NOT NULL,
    user_surname   NVARCHAR2(20) NOT NULL,
    user_email     NVARCHAR2(50) NOT NULL,
    user_phone     VARCHAR2(15),
    user_password  VARCHAR2(60 CHAR) NOT NULL,
    end_date       DATE
);

ALTER TABLE user_table ADD CONSTRAINT user_table_pk PRIMARY KEY ( user_id );

CREATE TABLE user_token (
    user_table_user_id  NUMBER(9) NOT NULL,
    token_token_id      NUMBER(9) NOT NULL
);

CREATE UNIQUE INDEX user_token__idx ON
    user_token (
        token_token_id
    ASC );

CREATE UNIQUE INDEX user_token__idxv1 ON
    user_token (
        user_table_user_id
    ASC );

ALTER TABLE user_token
    ADD CONSTRAINT user_token_token_fk FOREIGN KEY ( token_token_id )
        REFERENCES token ( token_id );

ALTER TABLE user_token
    ADD CONSTRAINT user_token_user_table_fk FOREIGN KEY ( user_table_user_id )
        REFERENCES user_table ( user_id );

/*======ADDED MANUALLY=======*/

ALTER TABLE user_table
ADD CONSTRAINT email_unique UNIQUE (user_email);

ALTER TABLE user_table
ADD CONSTRAINT phone_unique UNIQUE (user_phone); 

--ALTER TABLE token
--ADD CONSTRAINT token_unique UNIQUE (user_token);


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             2
-- CREATE INDEX                             1
-- ALTER TABLE                              3
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
