create or replace TRIGGER TRG_INSERT_USER_TABLE
BEFORE INSERT ON USER_TABLE
FOR EACH ROW
BEGIN
  :NEW.user_id:=USER_TABLE_ID_SEQ.NEXTVAL;
END;

create or replace TRIGGER TRG_INSERT_TOKEN
BEFORE INSERT ON TOKEN
FOR EACH ROW
BEGIN
  :NEW.token_id:=TOKEN_ID_SEQ.NEXTVAL;
END;

CREATE OR REPLACE TRIGGER TRG_NEW_DATE_USER_TABLE
BEFORE INSERT ON USER_TABLE
FOR EACH ROW
BEGIN
    :NEW.end_date := CURRENT_DATE + 14;
END;

CREATE OR REPLACE TRIGGER TRG_UPDATE_DATE_USER_TABLE
BEFORE UPDATE ON USER_TABLE
FOR EACH ROW
BEGIN
    IF :NEW.end_date = NULL THEN
        :new.end_date := NULL;
    ELSE
        :new.end_date := CURRENT_DATE + 14;
    END IF;
END;