const OrdersActionTypes = {
    FETCH_USER_ORDERS_START: 'FETCH_USER_ORDERS_START',
    FETCH_USER_ORDERS_SUCCESS: 'FETCH_USER_ORDERS_SUCCESS',
    FETCH_USER_ORDERS_FAILURE: 'FETCH_USER_ORDERS_FAILURE',
    SET_ORDER_HIDDEN: 'SET_ORDER_HIDDEN',
};

export default OrdersActionTypes;
