ALTER TABLE DBPROJECT.SENTENCES
 DROP PRIMARY KEY CASCADE;

DROP TABLE DBPROJECT.SENTENCES CASCADE CONSTRAINTS;

CREATE TABLE DBPROJECT.SENTENCES
(
  SENTENCE_ID  INTEGER                          NOT NULL,
  FK_HIKE_ID   INTEGER                          NOT NULL,
  START_DATE   DATE                             NOT NULL
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX DBPROJECT.SENTENCE_PK ON DBPROJECT.SENTENCES
(SENTENCE_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER DBPROJECT.SENTENCESSEQ
BEFORE INSERT
ON DBPROJECT.SENTENCES
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column SENTENCE_ID
  :new.SENTENCE_ID := SENTENCES_SEQ.nextval;
END SENTENCESSEQ;
/


ALTER TABLE DBPROJECT.SENTENCES ADD (
  CONSTRAINT SENTENCE_PK
  PRIMARY KEY
  (SENTENCE_ID)
  USING INDEX DBPROJECT.SENTENCE_PK
  ENABLE VALIDATE);

ALTER TABLE DBPROJECT.SENTENCES ADD (
  CONSTRAINT HIKE_FK 
  FOREIGN KEY (FK_HIKE_ID) 
  REFERENCES DBPROJECT.HIKES (HIKE_ID)
  ON DELETE SET NULL
  ENABLE VALIDATE);
