CREATE SEQUENCE sq_Note
START WITH 1 
INCREMENT BY 1 
NOMAXVALUE;

CREATE OR REPLACE TRIGGER tr_note before INSERT ON "Note" FOR each row
BEGIN
  SELECT sq_Note.NEXTVAL
  INTO :new.id
  FROM dual;
END;