const AdminActionTypes = {
    ADMIN_GET_ALL_USERS_ORDERS_START: 'ADMIN_GET_ALL_USERS_ORDERS_START',
    ADMIN_GET_ALL_USERS_ORDERS_SUCCESS: 'ADMIN_GET_ALL_USERS_ORDERS_SUCCESS',
    ADMIN_GET_ALL_USERS_ORDERS_FAILURE: 'ADMIN_GET_ALL_USERS_ORDERS_FAILURE',
    ADMIN_GET_ALL_USERS_START: 'ADMIN_GET_ALL_USERS_START',
    ADMIN_GET_ALL_USERS_SUCCESS: 'ADMIN_GET_ALL_USERS_SUCCESS',
    ADMIN_GET_ALL_USERS_FAILURE: 'ADMIN_GET_ALL_USERS_FAILURE',
    ADMIN_GET_ALL_ORDERS_START: 'ADMIN_GET_ALL_ORDERS_START',
    ADMIN_GET_ALL_ORDERS_SUCCESS: 'ADMIN_GET_ALL_ORDERS_SUCCESS',
    ADMIN_GET_ALL_ORDERS_FAILURE: 'ADMIN_GET_ALL_ORDERS_FAILURE',
    ADMIN_UPDATE_ORDER_STATUS_START: 'ADMIN_UPDATE_ORDER_STATUS_START',
    ADMIN_UPDATE_ORDER_STATUS_SUCCESS: 'ADMIN_UPDATE_ORDER_STATUS_SUCCESS',
    ADMIN_UPDATE_ORDER_STATUS_FAILURE: 'ADMIN_UPDATE_ORDER_STATUS_FAILURE',
    ADMIN_GET_USERS_TO_ORDERS: 'ADMIN_GET_USERS_TO_ORDERS',
}

export default AdminActionTypes;