const CartActionTypes = {
    TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
    ADD_ITEM: 'ADD_ITEM',
    REMOVE_ITEM: 'REMOVE_ITEM',
    CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
    CLEAR_CART: 'CLEAR_CART',
    CREATE_NEW_ORDER_START: 'CREATE_NEW_ORDER_START',
    CREATE_NEW_ORDER_SUCCESS: 'CREATE_NEW_ORDER_SUCCESS',
    CREATE_NEW_ORDER_FAILURE: 'CREATE_NEW_ORDER_FAILURE',
};

export default CartActionTypes;
