ALTER TABLE DBPROJECT.FEATURE
 DROP PRIMARY KEY CASCADE;

DROP TABLE DBPROJECT.FEATURE CASCADE CONSTRAINTS;

CREATE TABLE DBPROJECT.FEATURE
(
  FEATURE_ID  INTEGER                           NOT NULL,
  FK_USER_ID  INTEGER,
  BIRTH_DATE  DATE,
  EQUIPMENT   INTEGER,
  HEALTHY     INTEGER,
  HEIGHT      INTEGER,
  WEIGHT      FLOAT(126)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX DBPROJECT.FEATURE_PK ON DBPROJECT.FEATURE
(FEATURE_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER DBPROJECT.FEATURE_TRG
BEFORE INSERT
ON DBPROJECT.FEATURE
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column FEATURE_ID
  :new.FEATURE_ID := FEATURE_SEQ.nextval;
END FEATURE_TRG;
/


ALTER TABLE DBPROJECT.FEATURE ADD (
  CONSTRAINT FEATURE_PK
  PRIMARY KEY
  (FEATURE_ID)
  USING INDEX DBPROJECT.FEATURE_PK
  ENABLE VALIDATE);
